name: Mark Notifications as Done

on:
  schedule:
    - cron: "59 22 * * *" # Runs at 10:59 PM UTC (11:59 PM Amsterdam Time in winter)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Log Current Time (Debugging)
        run: date -u && date

      - name: Install Dependencies
        run: npm install

      - name: Run Automation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        run: |
          echo "Token exists: ${{ secrets.GH_PAT != '' }}"
          echo "Username exists: ${{ secrets.GH_USERNAME != '' }}"
          node src/index.js
